// iea 1 is check the date, and show the month of or following ie if it's march show april start instead of august. so april august start vs august april start
// if the application deadline is within a month or two, add a line under program starts in read saying deadline approcahing, concern to much 
const programs = [
	//problem for online and on campus program starts being different, how to handle!?	
//CERTIFICATES
	  {
	    "id": "c1",
	    "name": "Catholic School Leadership",
	    "description": "",
	    "programLink": "/program/catholic-school-leader-masters-certificate",
	    "formats": ["Online"],
	    "buckets": "",
	    "creditHours": "12",
  		"degreeType": {
  			"masters": false,
  			"dual_degree": false,
  			"doctorate": false,
  			"certificate": true,
  		},
	    "Program starts": ["August", "January", "June"],
	    
	  },
	  {
	    "id": "c2",
	    "name": "Financial Psychology and Behavioral Finance",
	    "description": "",
	    "programLink": "/program/Financial-Psychology-and-Behavioral-Finance-Certificate",
	    "formats": ["Online"],
	    "buckets": "",
	    "creditHours": "15",
    		"degreeType": {
    			"masters": false,
    			"dual_degree": false,
    			"doctorate": false,
    			"certificate": true,
    		},
	    "Program starts": ["August","October", "January", "March", "June"],
	  },
	  {
	    "id": "c3",
	    "name": "Health Care Ethics",
	    "description": "",
	    "programLink": "/program/health-care-ethics-ms",
	    "formats": ["Online"],
	    "buckets": "",
	    "creditHours": "15",
  		"degreeType": {
  			"masters": false,
  			"dual_degree": false,
  			"doctorate": false,
  			"certificate": true,
  		},
	    "Program starts": ["August", "January", "May"],
	  },
	  {
	    "id": "c4",
	    "name": "Health Care Collaboration and Conflict Management",
	    "description": "",
	    "programLink": "/program/health-care-collaboration-and-conflict-management-graduate-certificate",
	    "formats": "Online*, Hybrid",
	    "buckets": "",
	    "creditHours": "15",
  		"degreeType": {
  			"masters": false,
  			"dual_degree": false,
  			"doctorate": false,
  			"certificate": true,
  		},
	    "Program starts": ["August", "January", "May"],
	    
	  },
	  {
	    "id": "c5",
	    "name": "Healthcare Management",
	    "description": "",
	    "programLink": "/program/healthcare-management-graduate-certificate",
	    "formats": "Online",
	    "buckets": "",
	    "creditHours": "15",
  		"degreeType": {
  			"masters": false,
  			"dual_degree": false,
  			"doctorate": false,
  			"certificate": true,
  		},
	    "Program starts": ["August", "January"],
	   
	  },
	  {
	    "id": "c6",
	    "name": "Lifestyle Medicine",
	    "description": "",
	    "programLink": "/program/lifestyle-medicine-graduate-certificate",
	    "formats": "Online",
	    "buckets": "",
	    "creditHours": "15",
  		"degreeType": {
  			"masters": false,
  			"dual_degree": false,
  			"doctorate": false,
  			"certificate": true,
  		},
	    "Program starts": ["August", "January"],
	    
	  },
	  {
	    "id": "c7",
	    "name": "Negotiation and Conflict Resolution",
	    "description": "",
	    "programLink": "/program/negotiation-and-conflict-resolution-graduate-certificate",
	    "formats": ["Online*", "Hybrid"],
	    "buckets": "",
	    "creditHours": "16",
  		"degreeType": {
  			"masters": false,
  			"dual_degree": false,
  			"doctorate": false,
  			"certificate": true,
  		},
	    "Program starts": ["August", "January", "May"],
	    
	  },
	  {
	    "id": "c8",
	    "name": "Nursing (Post-Graduate Certificate)",
	    "description": "",
	    "programLink": "/program/nursing-post-graduate-certificate",
	    "formats": "Online",
	    "buckets": "",
	    "creditHours": "18-31",
  		"degreeType": {
  			"masters": false,
  			"dual_degree": false,
  			"doctorate": false,
  			"certificate": true,
  		},
	    "Program starts": "Starts vary by certificate",
	    
	  },
	  {
	    "id": "c9",
	    "name": "Organizational Leadership",
	    "description": "",
	    "programLink": "/program/organizational-leadership-graduate-certificate",
	    "formats": "Online",
	    "buckets": "",
	    "creditHours": "15",
  		"degreeType": {
  			"masters": false,
  			"dual_degree": false,
  			"doctorate": false,
  			"certificate": true,
  		},
	    "Program starts": "August, January",
	    
	  },
 // Masters
	  {
	 "id": "m1",
	 "name": "Accounting (Master of Accounting)",
	 "description": "Advance your career in accounting and position yourself for CPA designation.",
	 "program link": "/program/accounting-mac",
	 "formats": ["On-campus"],
	 "buckets": ["Business"],
	 "credit hours": "33",
  	 "degreeType": {
  	 	"masters": true,
  	 	"dual_degree": false,
  	 	"doctorate": false,
  	 	"certificate": false,
	 },
	 "Program starts online": [],
	 "Program starts campus": ["August", "February", "May", "July"]
	 },
	  {
		  "id": "m2",
		  "name": "Biomedical Sciences (Master of Science)",
		  "description": "",
		  "program link": "/program/biomedical-sciences-ms",
		  "formats": ["On-Campus"],
		  "buckets": [],
		  "credit hours": "30",
		  "degreeType": {
   	   		"masters": true,
   	   		"dual_degree": false,
   	   		"doctorate": false,
   	   		"certificate": false,
	   		},
			"Program starts online": [],
			"Program starts campus": ["August"],
	   },
	   {
	"id": "m3",
	"name": "Business Administration (MBA)",
	"description": "Earn your MBA through a highly customizable, flexible program designed to fit the busy lifestyles and career demands of working business professionals.",
	"program link": "/program/Business-Administration-MBA",
	"formats": ["On-campus", "Online", "Hybrid"],
	"buckets": ["Business"],
	"credit hours": "33",
	"degreeType": {
		"masters": true,
		"dual_degree": false,
		"doctorate": false,
		"certificate": false,
	},
	"Program starts online": ["August", "October", "January", "March", "June"],
	"Program starts campus": ["August", "December", "February", "May", "July"],
	},
			  {
			    "id": "m4",
			    "name": "Business Intelligence and Analytics (Master of Science)",
			    "description": "Develop skills to manage a wealth of data, gain insights, and effectively communicate findings to administrators in your organization.",
			    "program link": "/program/Business-Intelligence-and-Analytics-MSBIA",
			    "formats": ["On-campus", "Online"],
			    "buckets": ["Business"],
			    "credit hours": "33",
    		  		"degreeType": {
    		  			"masters": true,
    		  			"dual_degree": false,
    		  			"doctorate": false,
    		  			"certificate": false,
						},
			    "Program starts online": ["August", "February", "May",  "July"],
			    "Program starts campus": ["August", "January"],
			  },
			  {
			    "id": "m5",
			    "name": "Christian Spirituality (Master of Science)",
			    "description": "",
			    "program link": "/program/christian-spirituality-ma",
			    "formats": ["On-Campus", "Hybrid"],
			    "buckets": [],
			    "credit hours": "33",
    		  		"degreeType": {
    		  			"masters": true,
    		  			"dual_degree": false,
    		  			"doctorate": false,
    		  			"certificate": false,
						},
			    "Program starts campus": ["August"],
			  },
			  {
			    "id": "m6",
			    "name": "Clinical Anatomy (Master of Science)",
			    "description": "",
			    "program link": "/program/clinical-anatomy-ms",
			    "formats": ["On-Campus"],
			    "buckets": [],
			    "credit hours": "36",
    		  		"degreeType": {
    		  			"masters": true,
    		  			"dual_degree": false,
    		  			"doctorate": false,
    		  			"certificate": false,
						},
			    "Program starts online": [],
			    "Program starts campus": ["August"],
			  },
			  {
			    "id": "m7",
			    "name": "Clinical and Translational Science (Master of Science)",
			    "description": "",
			    "program link": "/program/clinical-and-translational-science-ms",
			    "formats": ["On-Campus"],
			    "buckets": [],
			    "credit hours": "30",
    		  		"degreeType": {
    		  			"masters": true,
    		  			"dual_degree": false,
    		  			"doctorate": false,
    		  			"certificate": false,
						},
			    "Program starts online": [],
			    "Program starts campus": ["August", "January", "June"],
			  },
			  {
			    "id": "m8",
			    "name": "Creative Writing (Master of Fine Arts)",
			    "description": "",
			    "program link": "/program/creative-writing-mfa",
			    "formats": ["On-Campus"],
			    "buckets": [],
			    "credit hours": "48",
    		  		"degreeType": {
    		  			"masters": true,
    		  			"dual_degree": false,
    		  			"doctorate": false,
    		  			"certificate": false,
						},
			    "Program starts online": [],
			    "Program starts campus": ["August", "January"],
			  },
			  {
			    "id": "m9",
			    "name": "Educational Leadership (Master of Science)",
			    "description": "Position yourself for a leadership role in education through a master�s program tailored to both public and private school educators. Choose from specializations in School Administration or Teacher Leadership.",
			    "program link": "/program/Educational-Leadership-MS",
			    "formats": ["Online"],
			    "buckets": ["Education"],
			    "credit hours": "36",
    		  		"degreeType": {
    		  			"masters": true,
    		  			"dual_degree": false,
    		  			"doctorate": false,
    		  			"certificate": false,
						},
			    "Program starts online": ["June"],
			    "Program starts campus": [],
			  },
			  {
			    "id": "m10",
			    "name": "Elementary School Teaching (Master of Education)",
			    "description": "",
			    "program link": "/program/elementary-school-teaching-med",
			    "formats": ["On-Campus", "Accelerated"],
			    "buckets": ["Education"],
			    "credit hours": "41",
    		  		"degreeType": {
    		  			"masters": true,
    		  			"dual_degree": false,
    		  			"doctorate": false,
    		  			"certificate": false,
						},
			    "Program starts online": [],
			    "Program starts campus": ["May"],
			  },
			  {
			    "id": "m11",
			    "name": "Emergency Medical Services (MSEMS)",
			    "description": "Prepare for a leadership role in EMS through this master�s program tailored to EMS and healthcare professionals with several years of experience in EMS.",
			    "program link": "/program/Emergency-Medical-Services-MSEMS",
			    "formats": ["Online"],
			    "buckets": [],
			    "credit hours": "",
    		  		"degreeType": {
    		  			"masters": true,
    		  			"dual_degree": false,
    		  			"doctorate": false,
    		  			"certificate": false,
						},
			    "Program starts online": ["August", "January"],
			    "Program starts campus": [],
			  },
			  {
			    "id": "m12",
			    "name": "English (Master of Arts)",
			    "description": "",
			    "program link": "/program/english-ma",
			    "formats": ["On-Campus"],
			    "buckets": ["Education"],
			    "credit hours": "33-36",
    		  		"degreeType": {
    		  			"masters": true,
    		  			"dual_degree": false,
    		  			"doctorate": false,
    		  			"certificate": false,
						},
			    "Program starts online": [],
			    "Program starts campus": ["August"],
			  },
			  {
			    "id": "m13",
			    "name": "Executive Healthcare MBA (Master of Business Administration)",
			    "description": "This accelerated 18-month program is designed to position those working in healthcare to take the next step into an administrative role in healthcare management.",
			    "program link": "/program/Executive-Healthcare-MBA",
			    "formats": ["Hybrid", "Accelerated"],
			    "buckets": "Healthcare",
			    "credit hours": "45",
    		  		"degreeType": {
    		  			"masters": true,
    		  			"dual_degree": false,
    		  			"doctorate": false,
    		  			"certificate": false,
						},
			    "Program starts online": ["October"],
			    "Program starts campus": [],
			  },
			  {
			    "id": "m14",
			    "name": "Finance (Master of Finance)",
			    "description": "Take a deep dive into the field of finance through a flexible master�s program that can be customized to meet your professional goals.",
			    "program link": "/program/Finance-MFin",
			    "formats": ["On-campus", "Online", "Hybrid"],
			    "buckets": ["Business"],
			    "credit hours": "33",
    		  		"degreeType": {
    		  			"masters": true,
    		  			"dual_degree": false,
    		  			"doctorate": false,
    		  			"certificate": false,
						},
			    "Program starts online": ["August", "October", "January", "March", "June"],
			    "Program starts campus": [],
			  },
			  {
			    "id": "m15",
			    "name": "Health and Wellness Coaching (Master of Science)",
			    "description": "Empower individuals to take charge of their own health by teaching life-changing healthy behaviors and ways to sustain them.",
			    "program link": "/program/health-and-wellness-coaching-ms",
			    "formats": ["Online"],
			    "buckets": ["Healthcare"],
			    "credit hours": "36",
    		  		"degreeType": {
    		  			"masters": true,
    		  			"dual_degree": false,
    		  			"doctorate": false,
    		  			"certificate": false,
						},
			    "Program starts online": ["August", "January"],
			    "Program starts campus": [],
			  },
			  {
			    "id": "m16",
			    "name": "Health Care Ethics (Master of Science)",
			    "description": "Understand and apply critical thinking to respond to ethical issues that arise in health care.",
			    "program link": "/program/health-care-ethics-ms",
			    "formats": ["Online"],
			    "buckets": ["Healthcare"],
			    "credit hours": "33",
    		  		"degreeType": {
    		  			"masters": true,
    		  			"dual_degree": false,
    		  			"doctorate": false,
    		  			"certificate": false,
						},
			    "Program starts online": ["August", "January", "May"],
			    "Program starts campus": [],
			  },
			  {
			    "id": "m17",
			    "name": "Healthcare Management (Master of Science)",
			    "description": "Position yourself for a managerial role within a number of health care organizations while preparing to earn the highly-regarded FACHE certification.",
			    "program link": "/program/healthcare-management-mhm",
			    "formats": ["Online"],
			    "buckets": ["Healthcare"],
			    "credit hours": "48-51",
    		  		"degreeType": {
    		  			"masters": true,
    		  			"dual_degree": false,
    		  			"doctorate": false,
    		  			"certificate": false,
						},
			    "Program starts online": ["August", "January"],
			    "Program starts campus": [],
			  },
			  {
			    "id": "m18",
			    "name": "Investment Management and Financial Analysis (MIMFA)",
			    "description": "Launch or advance your career in the highly competitive fields of investment, security analysis and portfolio management through our CFA_ Institute affiliated MIMFA program.",
			    "program link": "/program/Investment-Management-and-Financial-Analysis-MIMFA",
			    "formats": ["On-campus", "Online", "Hybrid"],
			    "buckets": ["Business"],
			    "credit hours": "30",
    		  		"degreeType": {
    		  			"masters": true,
    		  			"dual_degree": false,
    		  			"doctorate": false,
    		  			"certificate": false,
						},
			    "Program starts online": ["August", "January", "June"],
			    "Program starts campus": ["August", "October", "January", "March", "June"],
			  },
			  {
			    "id": "m19",
			    "name": "Magis Catholic Teacher Corps (MS or Med)",
			    "description": "",
			    "program link": "/program/magis-catholic-teacher-corps-masters-degrees",
			    "formats": ["Hybrid"],
			    "buckets": ["Education"],
			    "credit hours": "34",
    		  		"degreeType": {
    		  			"masters": true,
    		  			"dual_degree": false,
    		  			"doctorate": false,
    		  			"certificate": false,
						},
			    "Program starts online": ["May"],
			    "Program starts campus": [],
			  },
			  {
			    "id": "m20",
			    "name": "Medical Microbiology and Immunology (Master of Science)",
			    "description": "",
			    "program link": "/program/medical-microbiology-and-immunology-ms",
			    "formats": ["On-Campus"],
			    "buckets": [],
			    "credit hours": "30",
    		  		"degreeType": {
    		  			"masters": true,
    		  			"dual_degree": false,
    		  			"doctorate": false,
    		  			"certificate": false,
						},
			    "Program starts online": ["August"],
			    "Program starts campus": [],
			  },
			  {
			    "id": "m21",
			    "name": "Medical Physics (Master of Science)",
			    "description": "",
			    "program link": "/program/medical-physics-ms",
			    "formats": ["On-Campus"],
			    "buckets": [],
			    "credit hours": "43",
    		  		"degreeType": {
    		  			"masters": true,
    		  			"dual_degree": false,
    		  			"doctorate": false,
    		  			"certificate": false,
						},
			    "Program starts online": [],
			    "Program starts campus": ["August", "January"]
			  },
			  {
			    "id": "m22",
			    "name": "Ministry (Master of Arts)",
			    "description": "Prepare to serve in a leadership role or other professional capacities within the Catholic church or other Christian denominations, or in a faith-based role outside the church.",
			    "program link": "/program/Ministry-MA",
			    "formats": ["Hybrid*"],
			    "buckets": [],
			    "credit hours": "46",
    		  		"degreeType": {
    		  			"masters": true,
    		  			"dual_degree": false,
    		  			"doctorate": false,
    		  			"certificate": false,
						},
			    "Program starts online": ["June"],
			    "Program starts campus": [],
			  },
			  {
			    "id": "m23",
			    "name": "Negotiation and Conflict Resolution (Master of Science)",
			    "description": "Learn the skills and techniques required to understand, manage and resolve conflict in a variety of settings.",
			    "program link": "/program/negotiation-and-conflict-resolution-ms",
			    "formats": ["Online*", "Hybrid"],
			    "buckets": ["Leadership", "Business"],
			    "credit hours": "33",
    		  		"degreeType": {
    		  			"masters": true,
    		  			"dual_degree": false,
    		  			"doctorate": false,
    		  			"certificate": false,
						},
			    "Program starts online": ["August", "October", "January", "March", J"uly"],
			    "Program starts campus": [],
			  },
			  {
			    "id": "m24",
			    "name": "Nursing (Master of Science)",
			    "description": "Advance your nursing career through Clinical Nurse Leader and Clinical Systems Administration tracks. Choose from specializations in cardiology, education, and oncology.",
			    "program link": "/program/nursing-msn",
			    "formats": ["Online*"],
			    "buckets": ["Healthcare"],
			    "credit hours": "37-46",
    		  		"degreeType": {
    		  			"masters": true,
    		  			"dual_degree": false,
    		  			"doctorate": false,
    		  			"certificate": false,
						},
			    "Program starts online": ["August", "January", "May"],
			    "Program starts campus": ""
			  },
			  {
			    "id": "m25",
			    "name": "Occupational Therapy (Master of Science) or Rehabilitation (Master of Science)",
			    "description": "",
			    "program link": "/program/ms-occupational-therapy-or-rehabilitation",
			    "formats": ["On-Campus"],
			    "buckets": [],
			    "credit hours": "39",
    		  		"degreeType": {
    		  			"masters": true,
    		  			"dual_degree": false,
    		  			"doctorate": false,
    		  			"certificate": false,
						},
			    "Program starts online": [],
			    "Program starts campus": ["August"],
			  },
			  {
			    "id": "m26",
			    "name": "Organizational Leadership (Master of Science)",
			    "description": "Develop the skills you need to inspire and navigate positive change in your workplace and community.",
			    "program link": "/program/organizational-leadership-ms",
			    "formats": ["Online"],
			    "buckets": ["Leadership", "Business"],
			    "credit hours": "36",
    		  		"degreeType": {
    		  			"masters": true,
    		  			"dual_degree": false,
    		  			"doctorate": false,
    		  			"certificate": false,
					},
			    "Program starts online": ["August", "January"],
			    "Program starts campus": [],
			  },
			  {
			    "id": "m27",
			    "name": "Pharmaceutical Sciences (Master of Science)",
			    "description": "",
			    "program link": "/program/pharmaceutical-sciences-ms",
			    "formats": ["On-Campus"],
			    "buckets": [],
			    "credit hours": "33",
    		  		"degreeType": {
    		  			"masters": true,
    		  			"dual_degree": false,
    		  			"doctorate": false,
    		  			"certificate": false,
					},
			    "Program starts online": [],
			    "Program starts campus": ["August"],
			  },
			  {
			    "id": "m28",
			    "name": "Pharmacology (Master of Science)",
			    "description": "",
			    "program link": "/program/pharmacology-ms",
			    "formats": ["On-Campus"],
			    "buckets": [],
			    "credit hours": "30",
  		  		"degreeType": {
  		  			"masters": true,
  		  			"dual_degree": false,
  		  			"doctorate": false,
  		  			"certificate": false,
				},
			    "Program starts online": [],
			    "Program starts campus": ["August"],
			  },
			  {
			    "id": "m29",
			    "name": "Physics (Master of Science)",
			    "description": "",
			    "program link": "/program/physics-ms",
			    "formats": ["On-Campus"],
			    "buckets": [],
			    "credit hours": "30-33",
  		  		"degreeType": {
  		  			"masters": true,
  		  			"dual_degree": false,
  		  			"doctorate": false,
  		  			"certificate": false,
				},
			    "Program starts online": [],
			    "Program starts campus": ["August", "January"],
			  },
			  {
			    "id": "m30",
			    "name": "Public Health (Master of Science)",
			    "description": "",
			    "program link": "/program/public-health-ms",
			    "formats": ["Online"],
			    "buckets": ["Healthcare"],
			    "credit hours": "44",
  		  		"degreeType": {
  		  			"masters": true,
  		  			"dual_degree": false,
  		  			"doctorate": false,
  		  			"certificate": false,
				},
			    "Program starts online": ["August", "January", "May"],
			    "Program starts campus": [],
			  },
			  {
			    "id": "m31",
			    "name": "School Counseling & Preventive Mental Health (Master of Science)",
			    "description": "",
			    "program link": "/program/School-Counseling-and-Preventive-Mental-Health-MS",
			    "formats": ["Online"],
			    "buckets": ["Education"],
			    "credit hours": "36-39",
  		  		"degreeType": {
  		  			"masters": true,
  		  			"dual_degree": false,
  		  			"doctorate": false,
  		  			"certificate": false,
				},
			    "Program starts online": ["June"],
			    "Program starts campus": [],
			  },
//doctorate
			  {
			      "id": "d1",
			      "name": "Biomedical Sciences (Doctorate)",
			      "description": "",
			      "program link": "/program/biomedical-sciences-phd",
			      "formats": ["On-Campus"],
			      "buckets": []],
			      "credit hours": "90",
    		  		"degreeType": {
    		  			"masters": false,
    		  			"dual_degree": false,
    		  			"doctorate": true,
    		  			"certificate": false,
  				},
			      "Program starts online": [],
			      "Program starts campus": ["August"],
			    },
			    {
			      "id": "d2",
			      "name": "Business Administration (DBA)",
			      "description": "Secure the credentials you need in order to be considered for top business leadership positions without quitting your current job through this hybrid cohort-styled DBA program.",
			      "program link": "/program/Doctorate-Business-Administration-DBA",
			      "formats": ["Hybrid*"],
			      "buckets": ["Business"],
			      "credit hours": "54",
    		  		"degreeType": {
    		  			"masters": false,
    		  			"dual_degree": false,
    		  			"doctorate": true,
    		  			"certificate": false,
  				},
			      "Program starts online": ["August"],
			      "Program starts campus": [],
			    },
			    {
			      "id": "d3",
			      "name": "Clinical and Translational Science (PhD)",
			      "description": "",
			      "program link": "/program/clinical-and-translational-science-phd",
			      "formats": ["On-Campus"],
			      "buckets": [],
			      "credit hours": "90",
    		  		"degreeType": {
    		  			"masters": false,
    		  			"dual_degree": false,
    		  			"doctorate": true,
    		  			"certificate": false,
  				},
			      "Program starts online": [],
			      "Program starts campus": ["August", "January"],
			    },
			    {
			      "id": "d4",
			      "name": "Interdisciplinary Leadership (EdD)",
			      "description": "See leadership from every angle and build your professional network through this practice-based, interdisciplinary leadership program.",
			      "program link": "/program/interdisciplinary-leadership-edd",
			      "formats": ["Online*"],
			      "buckets": ["Leadership"],
			      "credit hours": "60",
    		  		"degreeType": {
    		  			"masters": false,
    		  			"dual_degree": false,
    		  			"doctorate": true,
    		  			"certificate": false,
  				},
			      "Program starts online": ["August", "January"],
			      "Program starts campus": [],
			    },
			    {
			      "id": "d5",
			      "name": "Medical Microbiology and Immunology (Doctorate)",
			      "description": "",
			      "program link": "/program/medical-microbiology-and-immunology-phd",
			      "formats": ["On-Campus"],
			      "buckets": [],
			      "credit hours": "90",
    		  		"degreeType": {
    		  			"masters": false,
    		  			"dual_degree": false,
    		  			"doctorate": true,
    		  			"certificate": false,
  				},
			      "Program starts online": [],
			      "Program starts campus": ["August"],
			    },
			    {
			      "id": "d6",
			      "name": "Nursing (Doctor of Nursing Practice)",
			      "description": "Gain advanced scientific knowledge as well as practical hands-on skills to take your leadership role in nursing to new heights. Choose from various specializations and Advanced Practice Registered Nurse (APRN) tracks.",
			      "program link": "/program/doctor-nursing-practice-dnp",
			      "formats": ["Hybrid"],
			      "buckets": [],
			      "credit hours": "credit hours vary",
    		  		"degreeType": {
    		  			"masters": false,
    		  			"dual_degree": false,
    		  			"doctorate": true,
    		  			"certificate": false,
  				},
			      "Program starts online": ["August", "January", "May"],
			      "Program starts campus": [],
			    },
			    {
			      "id": "d7",
			      "name": "Occupational Therapy (OTD)",
			      "description": "Take an interprofessional approach to occupational therapy through the first entry-level OTD program in the nation. Choose from hybrid pathways to study on-campus, in the Greater Omaha area, in Anchorage, Alaska, or Denver, Colorado.",
			      "program link": "https://spahp.creighton.edu/future-students/doctor-occupational-therapy",
			      "formats": ["On-campus", "Hybrid"],
			      "buckets": [],
			      "credit hours": "124",
  		  		"degreeType": {
  		  			"masters": false,
  		  			"dual_degree": false,
  		  			"doctorate": true,
  		  			"certificate": false,
				},
			      "Program starts online": ["August"],
			      "Program starts campus": [],
			      
			    },
			    {
			      "id": "d8",
			      "name": "Pharmacy (PharmD)",
			      "description": "",
			      "program link": "https://spahp.creighton.edu/future-students/doctor-pharmacy",
			      "formats": ["On-campus", "Hybrid"],
			      "buckets": [],
			      "credit hours": "143",
  		  		"degreeType": {
  		  			"masters": false,
  		  			"dual_degree": false,
  		  			"doctorate": true,
  		  			"certificate": false,
				},
			      "Program starts online": ["August"],
			      "Program starts campus": [],
			    },
			    {
			      "id": "d9",
			      "name": "Pharmacology (Doctorate)",
			      "description": "",
			      "program link": "/program/pharmacology-phd",
			      "formats": ["On-Campus"],
			      "buckets": [],
			      "credit hours": "90",
    		  		"degreeType": {
    		  			"masters": false,
    		  			"dual_degree": false,
    		  			"doctorate": true,
    		  			"certificate": false,
  				},
			      "Program starts online": ["August"],
			      "Program starts campus": [],
			    },
			    {
			      "id": "d10",
			      "name": "Physical Therapy (DPT)",
			      "description": "Enhance your commitment to serving patients, society, and the physical therapy profession through a doctoral program dedicated to training competent and compassionate physical therapists.",
			      "program link": "https://spahp.creighton.edu/future-students/doctor-occupational-therapy",
			      "formats": ["On-Campus", "Hybrid"],
			      "buckets": [],
			      "credit hours": "135",
  		  		"degreeType": {
  		  			"masters": false,
  		  			"dual_degree": false,
  		  			"doctorate": true,
  		  			"certificate": false,
				},
			      "Program starts online": ["August"],
			      "Program starts campus": [],
			      
			    },
			    {
			      "id": "d11",
			      "name": "Post-Professional Occupational Therapy (PPOTD)",
			      "description": "",
			      "program link": "https://spahp.creighton.edu/future-students/post-professional-doctor-occupational-therapy",
			      "formats": ["Online*"],
			      "buckets": [],
			      "credit hours": {63},
  		  		"degreeType": {
  		  			"masters": false,
  		  			"dual_degree": false,
  		  			"doctorate": true,
  		  			"certificate": false,
				},
			      "Program starts online": ["August"],
			      "Program starts campus": [""],
			     
			    }
]
